<h1 style="
color:white;
background:#1E3A8A;
padding:15px;
text-align:center;
border-radius:10px;
font-family:Arial;
">
🚀 NumPy Complete Tutorial
</h1>

<h1 style="color:white; background-color:darkblue; padding:8px;">
NumPy Arrays 
</h1>

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6], dtype=float)
print(arr)

[1. 2. 3. 4. 5. 6.]


In [2]:
arr = np.array([[1,2,3],[1,2,3]])
print(arr)

[[1 2 3]
 [1 2 3]]


In [3]:
arr = np.zeros([5,5])
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
arr = np.ones([5,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
arr = np.empty(1)
print(arr)

[1.]


In [8]:
arr = np.full([2,3],7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [20]:
arr = np.eye(7)
print(arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [21]:
arr = np.identity(7)
print(arr)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [22]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [24]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [26]:
arr = np.logspace(0,10,3)
print(arr)

[1.e+00 1.e+05 1.e+10]
